services:
  backend:
    build: ./backend
    container_name: stt-b
    ports:
      - "8000:8010"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - qdrant

  frontend:
    build: ./app
    container_name: stt-f
    ports:
      - "3010:3010"
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      - backend
    stdin_open: true
    tty: true

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage

configs:
  qdrant_config:
    content: |
      log_level: INFO
